char* UIAGSVersionDate = "Вс 18 фев 2024 11:07:11";
char* versionDate = "Вс 18 фев 2024 11:07:11";
char* versionDateStr = "date:=Вс 18 фев 2024 11:07:11";
char* clearcaseView = "/view/igor";
char* clearcaseViewStr = "view:=/view/igor";
char* clearcaseConfigSpec = "\nelement * CHECKEDOUT\nelement * /main/CDEV_LATEST\nelement * /main/LATEST\n";
char* clearcaseConfigSpecStr = "configSpec:=element * CHECKEDOUTelement * /main/CDEV_LATESTelement * /main/LATEST";
char* compileFlags = "-I/cfs/x/usrLocals/WS/glibc-2.28/install/include -I/usr/include  -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward  -I/usr/local/share -I/usr/local/share/include -B/usr/lib/gcc/x86_64-redhat-linux/8 -B/usr/libexec/gcc/x86_64-redhat-linux/8  -D__X86 -D__WS8  -Wno-write-strings -g -pthread";
char* compileFlagsStr = "g++:=-I/cfs/x/usrLocals/WS/glibc-2.28/install/include -I/usr/include  -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward  -I/usr/local/share -I/usr/local/share/include -B/usr/lib/gcc/x86_64-redhat-linux/8 -B/usr/libexec/gcc/x86_64-redhat-linux/8  -D__X86 -D__WS8  -Wno-write-strings -g -pthread";
char* kernel = "4.18.0-305.17.1.el8_4.x86_64";
char* kernelstr = "kernel:=4.18.0-305.17.1.el8_4.x86_64";
char* node = "acnlinc6.pbn.bnl.gov";
char* nodestr = "node:=acnlinc6.pbn.bnl.gov";
char* OSstr = "OS:=Red Hat Enterprise Linux release 8.4 (Ootpa)";
